audit_header: false
title: Central Texas Real Estate Video Blog with Ryan Smith
description: Our mission at Ryan Smith Home Selling Team is to be your best resource for Central Texas real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Ryan Smith Home Selling Team, your professional Central Texas Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Ryan Smith
  title:
  license_number:
  about_markdown: |
    Always feeling a natural interest in real estate, pursuing a career as a Realtor has been an exciting and rewarding experience! It's always a wonderful thing when someone's personality and interests compliment such an enjoyable passion, and I can't even think of doing anything else! We pride ourselves in our service to our clients, and thoroughly enjoy helping people through their real estate transactions!

    Achieving our clients' goals is our first priority, and it's also the true measure of success for any real estate agent! As for the past couple years, business has been absolutely PHENOMENAL! We've been able to steadily increase our market share in the local real estate market and continue selling an incredible number of homes. Ultimately, excelling in real estate comes down to the outstanding service and value you provide to your market and we truly count it a blessing to help so many great folks. I can't even begin to tell you how much I appreciate the opportunities you have given us to serve.
  brand: Ryan Smith Home Selling Team
  brokerage: Keller Williams Realty
  market: Central Texas
  address: 10266 W. Adams Ave. Central Texas, TX 76502
  phone: 254-213-5335
  phone_type:
  phone2:
  phone2_type:
  email: Ryan@RyanSmithHomes.com
  url: http://www.RyanSmithHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.ryansmithhomes.com/sell
  second_CTA_text: Home Search
  second_CTA_URL: https://www.ryansmithhomes.com/buy

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Central Texas Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.ryansmithhomes.com/sell

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Central Texas Home?"
    CTA_text2: "Search the entire MLS for your Central Texas home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.ryansmithhomes.com/buy

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ryansmithhomes
  linkedin_url: https://www.linkedin.com/pub/ryan-smith/28/3a0/a02
  youtube_url: https://www.youtube.com/channel/UCCXH2XT0creLsVXieHKaqJg
  twitter_url: https://twitter.com/RyanSmithTeam
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/ryansmithteam/
  trulia_url: http://www.trulia.com/profile/ryan-smith-agent-Central Texas-tx-2691376
  yelp_url: http://www.yelp.com/biz/ryan-smith-home-selling-team-Central Texas
  podcast_url:

podcast:
  title: 'Central Texas Real Estate Podcast with Ryan Smith'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Central Texas Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Ryan Smith Home Selling Team - your professional Central Texas Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Central Texas, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Ryan Smith'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Central Texas Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#6d6e71'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
